### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by jollyfunnybone** [CoolFool/Roxy#1]
stopped working like 3 days ago. says 

-----> nginx-buildpack app detected
tar (child): nginx-heroku-22.tgz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
 !     Push rejected, failed to compile nginx-buildpack app.
 !     Push failed

**Comment by CoolFool** [comment]
Fixed the nginx buildback, Can you verify if it works?

**Comment by jollyfunnybone** [comment]
yes it works now, thanks
